global:
  scrape_interval: 15s  # Prometheus coleta as métricas a cada 15 segundos

scrape_configs:
  - job_name: 'spring-boot-api'   # Nome do job para monitorar
    metrics_path: '/actuator/prometheus'  # Endpoint onde a API expõe métricas
    static_configs:
      - targets: ['localhost:8080']  # Endereço e porta da sua aplicação
