server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}            # Ex.: jdbc:mariadb://host:port/database
    username: ${DB_USERNAME}  # Usuário do banco
    password: ${DB_PASSWORD}  # Senha do banco
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update        # Use 'update' só em dev; em produção prefira 'validate' ou remova
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  application:
    name: api-monitorada

jwt:
  secret: umaChaveSecretaMuitoLongaEComplexaParaAssinarTokensJWT
  expiration: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: always
