server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/av1_database
    username: root
    password: 
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Só use update em dev, em produção prefira validate ou nada
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  application:
    name: api-monitorada

jwt:
  secret: umaChaveSecretaMuitoLongaEComplexaParaAssinarTokensJWT
  expiration: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html # Caminho para a interface do Swagger UI
    disable-swagger-default-url: true # Evita carregar a URL padrão do Swagger (Petstore)
  api-docs:
    path: /v3/api-docs # Caminho para os arquivos de definição da API (JSON/YAML)

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: always
